name : Two jobs with needs

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: first job
       run: echo "this is first job"
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name : second job
      run: echo " this will run after second job"